### PR TITLE
MultiactorCollaboration Script

### PR DESCRIPTION
**Pull request by awatson1978**
Not ready for merge yet.  Script is at least half done though.  Currently testing nightwatch exit codes on travis.

### CODE REVIEW

**Comment by awatson1978** [comment]
Huh.  Got that `Couldn't find an Embedly API key!` error again.

BUT!  The run exited with the proper exit code, telling Jenkins that the test failed, and we get our correct email and error reporting in the PR log.

So that's a success!  :)

**Comment by awatson1978** [comment]
Just as an fyi to what's going on here...

The Travis open-source/free usage tier is slow...  runs on very small machines, each with like 512mb or RAM (if that).  The servers themselves being slow isn't that much of a problem, because it somewhat simulates the effects of a server being filled to capacity and not having enough processor/ram to work with.  If our app can run on the slow tiny instances that are available on the free tier, it will probably work fine when given more resources.

The slow travis servers have exposed two problems with the Telescope app.  Both have to do with server/client communications and latency.

The first issue has to do with the autoforms pattern, which uses the submit action and calls a meteor method.  Perfectly normal and typical pattern; but it does circumvent the latency compensation infrastructure.  So, some of the tests are failing because of async delays which are blocking the calls.  In particular, the response time when inserting a post isn't resolving in a timely manner.  It works fine when on localhost.  Maybe even when run on a production grade infrastructure.  But when memory/cpu gets low, this is going to be a problem since we're not using latency compensation.

The second issue has to do with data prefetching.  Or rather, we're not really doing any, since the subscriptions are defined in the router `waitOn` clause.  The idea with `waitOn` is to avoid putting unnecessary subscriptions in a global context, and to get a fast initial pageload.  The trade-off is that putting subscriptions in a route definition will slow down that subsequent pageload.  Apparently, collaborations aren't responding in a timely manner.  Again, works fine on localhost and desktop environments.  But when we get onto mobile, laggy networks, or the servers get some load, it's liable to become an issue.  The solution here is to prefetch data, and get some of the subscriptions in a more global context (I think).

**Comment by rbaertsch** [comment]
We have a big compute cluster. Perhaps we should run the tests on our own hardware.

**Comment by awatson1978** [comment]
Well, that's certainly a possibility.  And when MedBook has 10K+ tests, I'd say it would probably even be recommended.  There's quite a bit we can do before we need to marshall those kinds of resources though.  And I'd really like to get the latency compensation working.  

This is pretty typical of projects being initially put under QA.  We've flushed out 3 or 4 bugs already; these are two more; and I'd bet we do another few dozen before the dust settles and things get real stable.

**Comment by rbaertsch** [comment]
In general, should we move subscriptions out of the router waitOn event?

**Comment by awatson1978** [comment]
That requires a nuanced answer.  In general, yes(ish).  It was a best practice about a year ago, and there are still some instances where it might make sense to use it.  But general thinking of late in the community seems to be moving away from it's use.  More specifically, people are moving reactivity out of the router all together.  

If you've heard of Flow Router, it was designed specifically to not have reactivity in the router with things like the waitOn event.  I myself stopped using `waitOn` 6 or 9 months ago.

The caveat is that we don't necessarily want to just dump the subscriptions into the global context.  And, more specifically, I'm a bit concerned about the performance of having a single-record subscription in the app at all.   

But, I'm not entirely sure that these are such pressing concerns that they need to be addressed right now.  Right now, I'd like to focus on getting the multiactor script written and passing green, rather than getting it running on travis.  

Also, there's another continuous integration service that's been gaining popularity in the Meteor community called Circle CI that is maybe worth looking into before we go rewriting all the subscriptions and/or deploying dedicated hardware.  Circle CI competes directly with Travis, and has the same basic user interface, the same webhooks with Github, the same type of reporting within GitHub and by email, same free-usage tier for open-source projects... and, being newer, it may be a bit faster and run the tests with less problems.  

https://circleci.com/

I haven't run anything on CircleCI, but [Mitar shared his config file in this thread](https://forums.meteor.com/t/testing-a-meteor-package-with-velocity-tinytest/734/8), and from an encapsulation perspective, I'd rather try to freeze what's going on within the Telescope repo as we get things under QA and do any extra development on the infrastructure, rather than rewriting the app as I go along to conform to one specific CI services indiosyncracies.   

If that doesn't work, I might be recommending that we run things on your own hardware.  But I'd really like to have the GitHub webhook integration.  That's the magic sauce that makes the test-driven-development really work.

**Pull request closed without merging**
